name: Deploy to TestPyPI

on:
  # push:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install CUDA
        run: |
          wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-ubuntu2004.pin
          sudo mv cuda-ubuntu2004.pin /etc/apt/preferences.d/cuda-repository-pin-600
          wget https://developer.download.nvidia.com/compute/cuda/11.5.0/local_installers/cuda-repo-ubuntu2004-11-5-local_11.5.0-495.29.05-1_amd64.deb
          sudo dpkg -i cuda-repo-ubuntu2004-11-5-local_11.5.0-495.29.05-1_amd64.deb
          sudo apt-key add /var/cuda-repo-ubuntu2004-11-5-local/7fa2af80.pub
          sudo apt-get update
          sudo apt-get -y install cuda

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      
      - name: Update Conda and channels
        run: |
          conda update conda --yes
          conda update --all --yes

      - name: Install build dependencies
        run: python -m pip install --upgrade pip setuptools wheel twine
      
      - name: Install project dependencies
        run: conda env create --file environment.yml && conda activate my_env

      - name: Build distribution package
        run: python setup.py sdist bdist_wheel

      - name: Upload to TestPyPI
        run: python3 -m twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TESTPYPI_TOKEN }}
          TWINE_REPOSITORY: testpypi
